### ISSUE TITLE
ML Track Conversions

### ISSUE THREAD

**Issue by anubhav9199** [kabirnagpal/ML-Track#8]
@kabirnagpal Can we interchange week 2 and week 3 as teaching the things which are linked is good. for example, we use a one-hot encode in logistic regression for the classification and label encoding in NLP. so, what you say it is really good I guess people get easy to catch things.

**Comment by anubhav9199** [comment]
@kabirnagpal we can also divide week second into different weeks where it is going to be used.

**Comment by kabirnagpal** [comment]
Any of these concepts can be applied to any datasets. Specifically if we consider larger datasets, which use both the concepts, just for some simple regression model. And although learning on the go is great, but that might lead to a large number of concepts being introduced to students, for a rather simple model like logistic regression. What do you say? @anubhavsharma430

**Comment by anubhav9199** [comment]
Well actually, that's right I think we can go with one single module containing all. I introduce it because I learn it on the go and I find it easy to learn as when we level up we get to know many things. Also, what we can do is we start with little difficulty and place it to the next level one by one. and remaining maths part I think we can go with the theory of maths that how and why the function does that work and rest tell them to use the function directly. We also provide links to scratch code if someone who has the curiosity to know more can browse further.
Also, we add some programming skills so that they can write modular code for there own benefit.
this can work in a good way. @kabirnagpal

**Comment by anubhav9199** [comment]
@kabirnagpal also can I be a contributor for this repository.

**Comment by kabirnagpal** [comment]
@anubhavsharma430 Please recommend all the changes you want. Also, make a pull request and add links to your repository into my notebooks. That way, in case a student wants to follow the maths will be directed to your respective code section.

**Comment by anubhav9199** [comment]
ok sure 
I'll do that soon.

**Comment by kabirnagpal** [comment]
@anubhavsharma430 Please keep pulling the changes to your forked repo, as we're also making relevant changes to our repo
